### PR TITLE
[TS] LPS-159349 Possible to Assign User Without Approver Role to Approve Tasks

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Dear Team,

Please let me know if there are any updates on the review.

Thank you and best regards,
István

**Comment by IstvanD** [comment]
Dear Team,

Please let me know if there are any updates on the review.

Thank you and best regards,
István

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by IstvanD** [comment]
Dear Team,

The test failures are not related to the solution.

Best regards,
István

**Comment by seltong** [comment]
Hi, @IstvanD 

I believe we can take basically the same approach of this [commit](https://github.com/brianchandotcom/liferay-portal/pull/120756/commits/c7e647da0feed3f08d7a5c5c1ef9a641105fb14e) and we can use the method _getAssignableUsers(companyId, workflowTaskId)_ instead use only the _workflowTaskAssignee_.

I believe we can do something like:
```
if ((workflowTaskAssignee.getAssigneeClassPK() != userId) &&
	!assignableUsers.contains(assigneeUserId)) {

	throw new PrincipalException.MustHavePermission(
		userId, WorkflowTask.class.getName(), workflowTaskId,
		ActionKeys.VIEW);
}
```

Could you please check if we can go ahead with this approach?

Best regards,
Selton

**Comment by IstvanD** [comment]
Hi @seltong thank you for your observations!
I changed the fix accordingly, however, I omitted the `workflowTaskAssignee.getAssigneeClassPK() != userId` condition check because it will be false in the current case.

**Comment by seltong** [comment]
Hi @IstvanD, makes sense. We don't need `workflowTaskAssignee.getAssigneeClassPK() != userId` condition check.

I saw your changes and investigated the code. We need to know if the user is an admin too, makes sense for me to do something like the code below to check it.

```
List<Long> assignableUserIds = ListUtil.toList(
    getAssignableUsers(companyId, workflowTaskId),
    UserModel::getUserId);

List<String> userRoles = ListUtil.toList(
    _roleLocalService.getUserRoles(assigneeUserId), Role::getName);

if (!userRoles.contains(RoleConstants.ADMINISTRATOR) &&
    !assignableUserIds.contains(assigneeUserId)) {

	throw new PrincipalException.MustHavePermission(
	    userId, WorkflowTask.class.getName(), workflowTaskId,
	    ActionKeys.VIEW);
}

```
In addition, I saw that something seems wrong in the `getAssignableUsers(companyId, workflowTaskId)` method related with ParentOrganizations. I will take a look at this as soon as possible to help you if you need, however I believe the adding the code below in the line 1043 can solve some of these issues.

```
Group kaleoTaskInstanceTokenGroup = GroupLocalServiceUtil.getGroup(
  kaleoTaskInstanceToken.getGroupId());

Organization childOrganization = _organizationLocalService.fetchOrganization(
  kaleoTaskInstanceTokenGroup.getClassPK());

List<Group> parentOrganizationGroups = null;

if (childOrganization != null) {

  List<Organization> organizations =
    _organizationLocalService.getParentOrganizations(
      childOrganization.getOrganizationId());

  if (organizations != null) {
    parentOrganizationGroups = ListUtil.toList(
      organizations,
      organization -> {
        try {
          return GroupLocalServiceUtil.
            getOrganizationGroup(
              kaleoTaskInstanceToken.getCompanyId(),
              organization.getOrganizationId());
        }
        catch (PortalException portalException) {
          if (_log.isWarnEnabled()) {
            _log.warn(portalException);
          }
        }

        return null;
      });
  }
}

if (parentOrganizationGroups != null) {
  for (Group group : parentOrganizationGroups) {
    assignableUsers.addAll(
      Stream.of(
        _userGroupRoleLocalService.
          getUserGroupRolesByGroupAndRole(
            group.getGroupId(), assigneeClassPK)
      ).flatMap(
        List::parallelStream
      ).map(
        userGroupRole -> {
          try {
            return userGroupRole.getUser();
          }
          catch (PortalException portalException) {
            if (_log.isWarnEnabled()) {
              _log.warn(portalException);
            }
          }

          return null;
        }
      ).filter(
        user ->
          (user != null) && user.isActive() &&
          (user.getUserId() != assignedUserId)
      ).collect(
        Collectors.toList()
      ));
  }
}
```

**Comment by IstvanD** [comment]
Hi @seltong 

Thank you again for checking the code.

The user that assigns the task doesn't need to be an administrator. The reviewer can assign a task back to the user for further work, and the user can reassign it back to the reviewer.

Concerning the `getAssignableUsers(companyId, workflowTaskId)` method: one problem that I discovered is that won't return any users if `assignWorkflowTaskToUser` is called from a workflow script, because the script's associated `kaleoTaskAssignment` will have an `assigneeClassPK` of 0.

Best regards,
István

**Comment by IstvanD** [comment]
Hi @seltong 
I'm closing this pull request as I'm rethinking the solution.

Best regards,
István

**Pull request closed without merging**
