### PR TITLE
LPS-147480

### PR DESCRIPTION
**Pull request by eliasantosf**
Story: [LPS-139394](https://issues.liferay.com/browse/LPS-139394)
Task: [LPS-147480](https://issues.liferay.com/browse/LPS-147480)

### CODE REVIEW

**Review by cgmonte — APPROVED** [review]

**Comment by cgmonte** [comment]
ci:test:sf

**Comment by cgmonte** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
