### PR TITLE
LPS-148387

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-148387

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Hi, @mbowerman

we will take a look at this,

Thanks!

**Comment by MarinhoFeliphe** [comment]
Just started reviewing :)

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:calendar

**Comment by seltong** [comment]
Just started reviewing :)

**Comment by MarinhoFeliphe** [comment]
ci:test:calendar

**Review by seltong — APPROVED** [review]

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
Hi @mbowerman, thanks for your work!

**Pull request closed without merging**
