### PR TITLE
LPS-148242 Not needed

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @MarinhoFeliphe, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @MarinhoFeliphe, can you please check if these failures are related to your changes? Thanks

**Pull request closed without merging**
