### PR TITLE
LPS-146633

### PR DESCRIPTION
**Pull request by naraandrade**
Story: [LPS-145296](https://issues.liferay.com/browse/LPS-145296)

### CODE REVIEW

**Review by cgmonte — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:stop

**Comment by naraandrade** [comment]
ci:stop

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
