### PR TITLE
LPS-146463 User still has permission to approve a task even after losing permission

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
@seltong Please, rebase your branch and resolve the conflicts.

**Comment by seltong** [comment]
Resent in [liferay-workflow#786](https://github.com/liferay-workflow/liferay-portal/pull/786)

**Pull request closed without merging**
