### PR TITLE
master | LPS-153172

### PR DESCRIPTION
**Pull request by davidtellolr**
Hi team,

This PR solves the problem described [here](https://issues.liferay.com/browse/LPS-153172).

The change consists of moving the logic to avoid sending notifications to the users who did the self-assignment from [DefaultTaskManagerImpl.java](https://github.com/liferay-zulu/liferay-portal/compare/master...davidtellolr:master_LPS-153172#diff-610091f99325d94b188a57f34c1d5abf4b381ea92a57bb57858b818e51c639d3) to [AssigneeNotificationRecipientBuilder.java](https://github.com/liferay-zulu/liferay-portal/compare/master...davidtellolr:master_LPS-153172#diff-794172f3ab09200992ab892c15c641575744e705bd241ad25bcfd1f74b3c5d16). In this way, the notifications to other users will be correctly sent.

Please, let me know if you have any doubt.

Regards,

David Tello

### CODE REVIEW

**Comment by davidtellolr** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
Hi @davidtellolr, The Zulu team will review your pull request

Thanks!

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
Hi @davidtellolr, I'll review your pull tomorrow,

sorry for delay, the Zulu team is busy due the low code initiative.

Thank you!

**Comment by davidtellolr** [comment]
Hi @MarinhoFeliphe ,

Could you tell me if you will be able to review this PR soon? We have a customer waiting for a ticket related to this problem. 

Thank you!

**Comment by MarinhoFeliphe** [comment]
Hi @davidtellolr,

I'm finishing the review :), sorry for delay.

**Comment by davidtellolr** [comment]
Hi @MarinhoFeliphe ,

No worries, I know that you are busy.

Thanks!

**Comment by MarinhoFeliphe** [comment]
Hi @davidtellolr,

Looks good to me!

Thank you!

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Pull request closed without merging**
