### PR TITLE
LPS-146798 Add next calendar booking info on the page

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
Related Issue: https://issues.liferay.com/browse/LPS-146798

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:calendar

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:calendar

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by liferay-forms** [comment]
ci:test:relevant

**Pull request closed without merging**
