### PR TITLE
Lps-157721: Change Notification link to use always use '/manage' as layout friendlyURL

### PR DESCRIPTION
**Pull request by kristofloneck**
Continues of this PR:
https://github.com/liferay-zulu/liferay-portal/pull/285

### CODE REVIEW

**Comment by kristofloneck** [comment]
ci:sf

**Comment by kristofloneck** [comment]
@liferay-zulu

**Comment by kristofloneck** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
Hi @kristofloneck, could you please check this semantic version failure?

```
 [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.portlet                  MINOR      20.0.0     20.0.0     20.1.0     VERSION INCREASE REQUIRED
     [exec]   <   class      com.liferay.portal.kernel.portlet.PortletURLFactoryUtil
     [exec]     +   method     create(javax.servlet.http.HttpServletRequest,java.lang.String,java.lang.String,boolean)
     [exec]       +   access     static
     [exec]       +   return     com.liferay.portal.kernel.portlet.LiferayPortletURL
     [exec]   <   interface  com.liferay.portal.kernel.portlet.PortletURLFactory
     [exec]     +   method     create(javax.servlet.http.HttpServletRequest,java.lang.String,java.lang.String,boolean)
     [exec]       +   access     abstract
     [exec]       +   return     com.liferay.portal.kernel.portlet.LiferayPortletURL
     [exec] [Baseline Warning] Bundle Version Change Recommended: 67.1.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/67.0.0/2218369777020497917c0d3eddb79ceeec75e535/com.liferay.portal.kernel-67.0.0.jar
```

**Comment by kristofloneck** [comment]
@seltong 
Checking it.

**Comment by kristofloneck** [comment]
Closed pr because needed to rebase the branch to current master. Opening new one soon.

**Pull request closed without merging**
