### PR TITLE
LPS-121020 Prevent index creation/removal requests from being triggered more than once for the same company index

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:workflow

**Comment by rafaprax** [comment]
Hey @lucasperj, Can you please help to scan these test results?

Thx

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:workflow

**Comment by lucasperj** [comment]
ci:test:relevant

**Comment by lucasperj** [comment]
ci:test:relevant

**Comment by lucasperj** [comment]
ci:test:workflow-metrics

**Comment by lucasperj** [comment]
ci:test:relevant

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Pull request closed without merging**
