### PR TITLE
LPS-152196 Adapt date columns to be filterable

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
Story: [LPS-152196](https://issues.liferay.com/browse/LPS-152196)

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by naraandrade** [comment]
Just started reviewing :)

**Pull request closed without merging**
