### PR TITLE
LPS-146615

### PR DESCRIPTION
**Pull request by naraandrade**
Story: [LPS-139392](https://issues.liferay.com/browse/LPS-139392)

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by cgmonte** [comment]
Just started reviewing :)

**Review by cgmonte — APPROVED** [review]

**Comment by cgmonte** [comment]
ci:forward

**Pull request closed without merging**
