### PR TITLE
[TS] LPS-149303 Recurring All Day Calendar Event are skipping months when the Time Zone is not UTC	

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Please note that the Calendar portlet's Time Zone has to be set to UTC+2 (same as the user's) for the correct display of the recurrences in the minicalendar.

Thank you and best regards,
István

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Hi @IstvanD,

This [functional test](https://testray.liferay.com/home/-/testray/case_results/1872614547?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1872614413%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) of the Calendar didin't passed I believe that it is related with this change, I'll run it on my machine to find out this test cover to know if we need to adapt the test or change something else.

Thank you!

**Comment by MarinhoFeliphe** [comment]
ci:test:calendar

**Comment by seltong** [comment]
Just started reviewing :)

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by seltong** [comment]
Just started reviewing :)

**Comment by seltong** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Dear Team,

I have tested the scenario LocalFile.NewEvent#AddAllDay but I couldn't reproduce the test failure.
The all-day event appears on the schedurer, as expected.

**Comment by MarinhoFeliphe** [comment]
Hi @IstvanD,

I ran this test in my machine and it didn't fail,

@anabuchmann could you check if this test (`NewEvent#AddAllDay`) is flacky, otherwise could you forward it manually?

Thank you!

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Comment by MarinhoFeliphe** [comment]
Hi @anabuchmann,

The test keeps failing, could you forward these changes?

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Comment by anabuchmann** [comment]
Manually forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/118881

**Pull request closed without merging**
