### PR TITLE
LPS-159222 Set transactional as readOnly instead of CTAware as production true

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:commerce

**Comment by MarinhoFeliphe** [comment]
ci:stop

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:object

**Comment by pyoo47** [comment]
ci:test:object (Moving original test invocation off an overloaded server)

**Comment by MarinhoFeliphe** [comment]
ci:test:object

**Pull request closed without merging**
