### PR TITLE
LPS-147408 Fix title translations in workflow save request

### PR DESCRIPTION
**Pull request by igor-franca**
https://issues.liferay.com/browse/LPS-147408

### CODE REVIEW

**Comment by M-IgorFranca** [comment]
ci:test:sf

**Comment by M-IgorFranca** [comment]
ci:test:relevant

**Comment by M-IgorFranca** [comment]
I had the opportunity to perform these testers locally and they worked, I will try again.

**Comment by M-IgorFranca** [comment]
ci:test:relevant

**Comment by M-IgorFranca** [comment]
Hello @naraandrade, you can verify if are everything ok with this tests? I will run the relevant one more time because i not find relation between this tests and my modification.

**Comment by MarinhoFeliphe** [comment]
Hi @M-IgorFranca, the relevant are failing but your changes are not related,

please rebase this branch with the upstream/master, push and run the relevant again because this issue is fixed on master.

Thank you,
Feliphe

**Comment by MarinhoFeliphe** [comment]
ci:stop

**Comment by MarinhoFeliphe** [comment]
Any questions feel free to contact me.

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by M-IgorFranca** [comment]
Thanks for explanation @MarinhoFeliphe!

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
