### PR TITLE
Revert "LPS-121020 Remove modelListener since the WorkflowMetricsPortalInstanceLifecycleListener will be executed when a Company is created (CompanyLocalService#addCompany) or when a company is registered (MainServlet#_initCompanies)."

This reverts commit 2902716127ac5130f988fb5ebc64123808afa7ad.

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Resent [here](https://github.com/brianchandotcom/liferay-portal/pull/117487)

**Pull request closed without merging**
