### PR TITLE
LPS-155358 SF

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
Story: [LPS-151877](https://issues.liferay.com/browse/LPS-151877)

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Pull request closed without merging**
