### PR TITLE
LPS-150829 Provide Validations tab

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:sf

**Comment by cgmonte** [comment]
Just started reviewing :)

**Comment by cgmonte** [comment]
Just started reviewing :)

**Comment by cgmonte** [comment]
Just started reviewing :)

**Comment by cgmonte** [comment]
Just started reviewing :)

**Comment by seltong** [comment]
ci:test:sf

**Comment by MariMalta** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Follow up here: #102

**Pull request closed without merging**
