### PR TITLE
[TS] LPS-149303 Recurring All Day Calendar Event are skipping months when the Time Zone is not UTC

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Hi @MarinhoFeliphe 

I have checked the tests.

The error message indicates an issue with the schema version
```
LIFERAY_ERROR: Spring Extender Unavailable Component Checker check result: 
Bundle {id: 816, name: com.liferay.calendar.service, version: 6.0.35}.
	Component with ID 150 is unavailable due to missing required dependencies:
		service dependency [com.liferay.portal.kernel.model.Release (&(release.bundle.symbolic.name=com.liferay.calendar.service)(&(release.schema.version>=4.2.0)(!(release.schema.version>=5.0.0)))(|(!(release.state=*))(release.state=0)))]
```
which was indeed increased to 4.2.1 in https://github.com/liferay-zulu/liferay-portal/pull/223/commits/08e666c5df69f3fe94c8fa6ba851134ef0a31900

but still falls in the 4.2.0 =< schemaversion < 5.0.0 range.

Therefore it doesn't seem to be related.

Regards,
István

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Hi @IstvanD,

Got it!, I'm taking a look.

Thanks!

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Resent here #239

cc: @IstvanD @anabuchmann

**Pull request closed without merging**
