### PR TITLE
LPS-147403 Display transition labels when user save it

### PR DESCRIPTION
**Pull request by MariMalta**

### CODE REVIEW

**Comment by MariMalta** [comment]
ci:test:sf

**Review by naraandrade — CHANGES_REQUESTED** [review]
@MariMalta As we are always calling `getXMLContent` passing publishing as true, it's not necessary anymore to receive this parameter. You can remove it and inside the `getXMLContent` function pass true directly as the last parameter for `serializeDefinition`. Thank you :)

**Comment by MariMalta** [comment]
ci:test:sf

**Comment by MariMalta** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
