### PR TITLE
LPS-152610

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-152610

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
I think that test failure was most likely caused by https://github.com/brianchandotcom/liferay-portal/pull/116797, not by my changes.

**Comment by mbowerman** [comment]
Test failure should be fixed with https://github.com/brianchandotcom/liferay-portal/commit/8386e32c4b0c2e7597f810cfcc8b15e4737540c8

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by seltong** [comment]
Just started reviewing :)

**Comment by MarinhoFeliphe** [comment]
Hi @laszlopap,

Sorry for the late reply,

Our team are working on to solve this problem and others with the same root cause,

We'll keep you updated

Thanks,
Feliphe

**Comment by MarinhoFeliphe** [comment]
Hi @laszlopap,

Sorry for the late reply,

Our team are working on to solve this problem and others with the same root cause,

We'll keep you updated

Thanks,
Feliphe

**Comment by mbowerman** [comment]
Hi @MarinhoFeliphe,

Would you be able to give a rough ETA on when your team will be able to fix this issue? This issue is currently impacting user experience on our client's production environment.

**Comment by AngeloJ** [comment]
Hi @MarinhoFeliphe, just following up to see if this issue has been prioritized and if there is rough ETA.

**Comment by MarinhoFeliphe** [comment]
Hi @AngeloJ,

We're receiving some requests from support team to solve 3 high priorities bugs from calendar (List below) and apparently these tickets are related to the same cause (All day events using UTC timezone).

Our PM and Brian Chan are looking for someone could support us in solving those bugs without stopping developing the new low code capabilities (our main goal for now).

At this moment, we still don't have a clear answer on how we will approach it, however [@Luiz Jardim](https://liferay.slack.com/team/U01AP0XH6K1) is working with Brian Chan to find a way to prioritize (probably we'll bring a answer early next week).

**Comment by MarinhoFeliphe** [comment]
- [LPS-149303](https://issues.liferay.com/browse/LPS-149303)
- [LPS-151947](https://issues.liferay.com/browse/LPS-151947)
- [LPS-152610](https://issues.liferay.com/browse/LPS-152610)

**Comment by MarinhoFeliphe** [comment]
ci:test:calendar

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Pull request closed without merging**
