### PR TITLE
LPS-157559 Return state value on getObjectFieldJSONObject

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
@seltong I'll rebase with master when your changes are synced up, so you can ignore the conflicts. Should I do any extra commits with autogenerated files because of the changes in my last commit?

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by seltong** [comment]
> @seltong I'll rebase with master when your changes are synced up, so you can ignore the conflicts. Should I do any extra commits with autogenerated files because of the changes in my last commit?

No, you don't need any extra commits. :)

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
