### PR TITLE
[TS] LPS-157713 Changing to PortalException

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

As per [Brian's request](https://github.com/brianchandotcom/liferay-portal/pull/120308#issuecomment-1183430961), I changed the exception type to PortalException.

Best regards,
István

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Dear Team,

The test failures are not related to the solution.

Best regards,
István

**Comment by seltong** [comment]
Hey guys, I will take a look at this test failures

**Comment by IstvanD** [comment]
Hi @seltong thank you for taking a look at it.
I'm looking forward to the results.

**Comment by seltong** [comment]
Hi @IstvanD sorry for delay.
I believe that we can close this pull request, but feel free to reopen it if you want.
I made some changes and ran the relevant again [here](https://github.com/liferay-zulu/liferay-portal/pull/283).

**Pull request closed without merging**
