### PR TITLE
LPS-147402 Make sure node id is unique

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by lucasperj** [comment]
ci:test:relevant

**Comment by lucasperj** [comment]
Sent here: https://github.com/brianchandotcom/liferay-portal/pull/117767. Thanks!

**Pull request closed without merging**
