### PR TITLE
LPS-149303 Testing the upgrade

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Hi @IstvanD, sorry for the late reply,

@anabuchmann took a look at the failures and noticed that the tests below are only failing in this pull request:

[CalendarUpgrade#ViewCalendarArchive625](https://testray.liferay.com/home/-/testray/case_results/1893514818/history?tab=result&hideFilterPin=true)
[CalendarUpgrade#ViewCalendarArchive621021](https://testray.liferay.com/home/-/testray/case_results/1893514812/history?tab=result&hideFilterPin=true)
[CalendarUpgrade#ViewCalendarArchive621015](https://testray.liferay.com/home/-/testray/cases/1311720559)

Please, could you take a look?


Thank you,
Feliphe

**Comment by IstvanD** [comment]
Hi @MarinhoFeliphe 

I have checked the three failed tests, and the VIEW_DAY_BUTTON is present in all three cases.
This is the same behavior on master.

**Comment by IstvanD** [comment]
Hi @MarinhoFeliphe 

Please let me know if there are updates about the review.

Thank you and best regards,
István

**Comment by MarinhoFeliphe** [comment]
Hi @IstvanD,

I'm going to check each test in the next week. This Friday is the deadline to deliver the last stories about the initiative that our team is working on.

Sorry for delay.

**Comment by IstvanD** [comment]
Hi @MarinhoFeliphe 

I hope all is going well.
Please let me know if there are updates about the review.

Thank you, and best regards,
István

**Comment by MarinhoFeliphe** [comment]
Hi @IstvanD, sorry for the late reply

Two security tickets appeared for me and a needed to handle them, I'm going to back to this task as soon as I finish them.

Best regards,
Feliphe

**Comment by IstvanD** [comment]
Hi @MarinhoFeliphe no problem.
Thank you for the update. I'm looking forward to the results of the review.

**Comment by MarinhoFeliphe** [comment]
Thanks @IstvanD!

**Pull request closed without merging**
