### PR TITLE
LPS-150931 Web Content Translation Page does not display repeatable Fields in Workflow's Notification view

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
Hi @IstvanD, I'm taking a look at this :)

Thank you!

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
Hi @IstvanD, on the workflow side, I just followed the LPS steps to make sure everything is working as expected,

but I believe you could send this pull request for the team responsible by Translation because you just changed their files, what do you think?

Thank you,
Feliphe

**Comment by IstvanD** [comment]
Hi @MarinhoFeliphe 

Thank you for reviewing these changes.
I may send a pull to the Translation team as well.

**Comment by MarinhoFeliphe** [comment]
I closed this pull request because this was resent [here](https://github.com/liferay-lima/liferay-portal/pull/2934)

Thank you!

**Pull request closed without merging**
