### PR TITLE
LPS-151901 Adapt the BuilderScreen and BuilderListItem to support the ObjectViewFilterColumn (Without Drag and Drop)

### PR DESCRIPTION
**Pull request by naraandrade**
Related Issue: https://issues.liferay.com/browse/LPS-151901

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by danvb112 — APPROVED** [review]
LGTM!

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
