### PR TITLE
LPS-147194 | LPS-147101

### PR DESCRIPTION
**Pull request by alinedoleron**
Tickets: 

- [LPS-147194](https://issues.liferay.com/browse/LPS-147194)
- [LPS-147101](https://issues.liferay.com/browse/LPS-147101)

Commits: 
[LPS-147194 Set default values for task and condition nodes](https://github.com/liferay-zulu/liferay-portal/pull/10/commits/f6d9c7f38a4c6e059040b58989a2a775dd8299d8)
[LPS-147194 Reoder xml tags according to the back end needs](https://github.com/liferay-zulu/liferay-portal/pull/10/commits/8ee104d68939770a480f94a1d3b361a872c58272)

https://user-images.githubusercontent.com/26491796/154562468-66576fd7-8904-43dc-aa33-505b1c475305.mp4

https://user-images.githubusercontent.com/26491796/154592413-4b42f796-00dd-4321-b78a-4815767a7693.mp4

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
