### PR TITLE
LPS-149303 For DSTShift method use displayTimeZone instead of calendarBooking.getTimeZone() when the booking is not all day

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:stop

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Hi @IstvanD,

In [this commit](https://github.com/liferay-zulu/liferay-portal/pull/290/commits/7c29456b3f06afd4729755ade0e7ccd5463fc6b3) I removed the upgrade process and the testes passed

please, could you remove this commit mentioned and try to find a way to fix [this problems](https://testray.liferay.com/home/-/testray/case_results?tab=runs&testrayBuildId=1913991438)?

Thank you and best regards,
Feliphe

**Comment by IstvanD** [comment]
Hi @MarinhoFeliphe 

I modified the upgrade process and sent a new pull request.
https://github.com/liferay-zulu/liferay-portal/pull/294

Could you please check it?

Thank you and best regards,
István

**Comment by MarinhoFeliphe** [comment]
Hi @IstvanD, of course!

Thank you!

**Comment by MarinhoFeliphe** [comment]
Resent here #294

**Pull request closed without merging**
