### PR TITLE
LPS-146664 - View and View Usage buttons are being displayed over MyWorkflowTaskPortlet

### PR DESCRIPTION
**Pull request by elocamp**

### CODE REVIEW

**Comment by fabiocampelo07** [comment]
ci:test:sf

**Comment by fabiocampelo07** [comment]
ci:test:sf

**Comment by fabiocampelo07** [comment]
ci:test:relevant

**Comment by fabiocampelo07** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Comment by fabiocampelo07** [comment]
Thanks, @naraandrade! :smile:

**Pull request closed without merging**
