### PR TITLE
LPS-146798 Add next calendar booking info on the page

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:calendar

**Comment by seltong** [comment]
ci:relevant:stop

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:calendar

**Comment by MarinhoFeliphe** [comment]
Just started reviewing :)

**Comment by MarinhoFeliphe** [comment]
ci:test:calendar

**Comment by MarinhoFeliphe** [comment]
resent here #34

**Pull request closed without merging**
