### PR TITLE
LPS-146463 Add unit test to cover the isApplicable method

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:forward

**Comment by seltong** [comment]
ci:stop

**Comment by seltong** [comment]
ci:test:calendar

**Comment by seltong** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:forward

**Comment by seltong** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
Just started reviewing :)

**Comment by MarinhoFeliphe** [comment]
resetn here #76

**Pull request closed without merging**
