### PR TITLE
LPS-156394 change Task to Task Name in My Workflow Tasks

### PR DESCRIPTION
**Pull request by igor-franca**
https://issues.liferay.com/browse/LPS-156394

### CODE REVIEW

**Comment by M-IgorFranca** [comment]
ci:test:sf

**Comment by M-IgorFranca** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
