### PR TITLE
LPS-146606 Add Actions to workflow

### PR DESCRIPTION
**Pull request by alinedoleron**
This PR is related to the story: [LPS-139393](https://issues.liferay.com/browse/LPS-139393)
Tasks:

- [LPS-146606](https://issues.liferay.com/browse/LPS-146606)
- [LPS-146607](https://issues.liferay.com/browse/LPS-146607)

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
