### PR TITLE
LPS-148578 SF

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
Related Issue: https://issues.liferay.com/browse/LPS-148578

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @MarinhoFeliphe, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @MarinhoFeliphe, can you please check if these failures are related to your changes? Thanks

**Pull request closed without merging**
