### PR TITLE
LPS-150826

### PR DESCRIPTION
**Pull request by naraandrade**
Story: [LPS-144474](https://issues.liferay.com/browse/LPS-144474)

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:stop

**Comment by seltong** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
Resent here: #113

**Pull request closed without merging**
