### PR TITLE
LPS-152512 Allow creating filter for metadata date fields

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
ci:stop

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
ci:stop

**Pull request closed without merging**
