### PR TITLE
[TS] LPS-152811

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
ci:test:sf

**Comment by crodriguezy** [comment]
ci:test:relevant

**Comment by crodriguezy** [comment]
Hi @MarinhoFeliphe, is there any reason why this PR was closed? I sent it to this user as asked in https://github.com/liferay-workflow/liferay-portal/pull/775

Thanks

**Comment by MarinhoFeliphe** [comment]
Hi @crodriguezy,

sorry to close this pull without comments,

I closed this pull due to the discussion we had on this [PTR](https://issues.liferay.com/browse/PTR-3047)

**Comment by MarinhoFeliphe** [comment]
Resent here #163

**Pull request closed without merging**
