### PR TITLE
[TS] LPS-150445

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @hongvo2308 @binhtran92

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
Hi @jonathanmccann, sorry for the late reply

these changes looks good to me!

I just tested to make sure that the behavior is the expected

Thank you!

**Comment by hongvo2308** [comment]
Hi @MarinhoFeliphe 
Thank you for reviewing this one. May I ask for the next steps on this one?
Thank you.

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Pull request closed without merging**
