### PR TITLE
LPS-148697 Fix ResourcePermission deletion for KaleoDefinitionVersion - LPS-145396 Subtask

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Related Issue: https://issues.liferay.com/browse/LPS-145396

When we delete some types of objects in Liferay, we are not deleting their ResourcePermission records, leaving some database wrong references.

For more information see parent LPS-145396

This subtask addresses the issue for Zulu team code

/cc @tinatian

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Hi @jorgediaz-lr, I'll take a look at this

Thank you!

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Just started reviewing :)

**Comment by liferay-forms** [comment]
Hey @jorgediaz-lr, can you please check if these failures are related to your changes? Thanks

**Comment by MarinhoFeliphe** [comment]
Hi @jorgediaz-lr,

The fails aren't related with your changes, so I'll forward this pull request.

Thank you for your work!

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Review by MarinhoFeliphe — APPROVED** [review]

**Pull request closed without merging**
