### PR TITLE
LPS-145574

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: https://issues.liferay.com/browse/LPS-145574

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Review by naraandrade — CHANGES_REQUESTED** [review]
@alinedoleron After importing the xml sample given in the ticket, the application crashes when we try to access the Diagram View. Could you take a look at this, please? Thanks :)

**Comment by alinedoleron** [comment]
> @alinedoleron After importing the xml sample given in the ticket, the application crashes when we try to access the Diagram View. Could you take a look at this, please? Thanks :)

Thank you very much, @naraandrade! I had removed the argument instead of ignore it. OMG! Sorry!

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by cgmonte** [comment]
Just started reviewing :)

**Review by cgmonte — APPROVED** [review]

**Comment by cgmonte** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Pull request closed without merging**
