### PR TITLE
LPS-157981 Notification Template is not created for the Calendar by default

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Dear Team,

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by IstvanD** [comment]
Dear Team,

Please let me know if there are any updates on the review.

Thank you and best regards,
István

**Comment by IstvanD** [comment]
Dear Team,

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by IstvanD** [comment]
Dear Team,

Do you have any updates on this review?

Thank you and best regards,
István

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Hi @IstvanD,

sorry for delay, we'll take a look at this.

Thank you,
Feliphe

**Comment by MarinhoFeliphe** [comment]
Hi @IstvanD,

Could you check if the fails are related with your changes,

Thank you,
Feliphe

**Comment by IstvanD** [comment]
Hi @MarinhoFeliphe 

I could verify that these test failures are not caused by the fix.

Best regards,
István

**Comment by MarinhoFeliphe** [comment]
HI @IstvanD,

I'm taking a look at this.

Thanks!

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
LGTM! :tada:

Thank you!

**Comment by MarinhoFeliphe** [comment]
ci:test:calendar

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Pull request closed without merging**
