### PR TITLE
LPS-149303 Rename AllDayCalendarBookingUpgradeProcess to CalendarBookingUpgradeProcess

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

As per [Brian's request](https://github.com/brianchandotcom/liferay-portal/pull/120836#issuecomment-1194743745), I renamed the class AllDayCalendarBookingUpgradeProcess to CalendarBookingUpgradeProcess, by editing the commits fdbd6ab1c13b991ab50888aef0a0062fa30a9cfe and fdf6cebd33b93c4016c809e90aee21aceaef4b89.

Could you please review?

Thank you and best regards.
István

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:upgrade

**Comment by MarinhoFeliphe** [comment]
Hi @IstvanD,

The fails displayed in the `relevant` are not related, but I believe that the some fails displayed in the `upgrade` are related.

could you take a look?

Thank you,
Feliphe

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:upgrade

**Comment by IstvanD** [comment]
Hi @MarinhoFeliphe I have updated the upgrade process.
Could you please run the tests again?

Thank you and best regards,
István

**Comment by IstvanD** [comment]
Hi @MarinhoFeliphe I have updated the upgrade process.
Could you please run the tests again?

Thank you and best regards,
István

**Comment by MarinhoFeliphe** [comment]
ci:test:upgrade

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Hi @IstvanD,

The fails seems not related so I forwarded it.

Thank you,
Feliphe

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Pull request closed without merging**
