### PR TITLE
LPS-146635 Get email address for user

### PR DESCRIPTION
**Pull request by MariMalta**
Story: [LPS-145296](https://issues.liferay.com/browse/LPS-145296)
Subtask: [LPS-146635](https://issues.liferay.com/browse/LPS-146635)

### CODE REVIEW

**Comment by MariMalta** [comment]
ci:test:sf

**Comment by MariMalta** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by lucasperj** [comment]
ci:forward

**Comment by pedro-michel** [comment]
@MariMalta and @lucasperj , can you guys take a look at this PR?

**Comment by lucasperj** [comment]
@pedro-michel needs to be reviewed iet. Thank you.

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
