### PR TITLE
LPS-156204 Remove Frontend Feature Flag of Objects support Categorization Framework

### PR DESCRIPTION
**Pull request by MariMalta**

### CODE REVIEW

**Comment by MariMalta** [comment]
ci:test:sf

**Comment by MariMalta** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
@seltong Could you please take a look at the test failures? Thanks :)

**Comment by seltong** [comment]
Just started reviewing :)

**Comment by seltong** [comment]
ci:help

**Comment by seltong** [comment]
Reset here #217

**Comment by seltong** [comment]
Resent here #217

**Pull request closed without merging**
