### PR TITLE
LPS-152165 Create Modal to add and edit default filter

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-152165

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:stop

**Comment by naraandrade** [comment]
@danvb112 SF failed, please check your changes.

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:forward

**Review by naraandrade — APPROVED** [review]

**Comment by lucasperj** [comment]
Sent here: https://github.com/brianchandotcom/liferay-portal/pull/116918#. Thank you.

**Pull request closed without merging**
