### PR TITLE
[TS]LPP-48153 > LPS-178041 "recipients" tag in workflow changes just by updating.

### PR DESCRIPTION
**Pull request by ces-locpham**
Hi team,
Please help me review this ticket.
https://issues.liferay.com/browse/LPS-177895
Thanks,
Loc
cc:@thienquach87

### CODE REVIEW

**Comment by thienquach87** [comment]
ci:test:sf

**Comment by thienquach87** [comment]
ci:test:relevant

**Comment by thienquach87** [comment]
I executed the  "blade gw formatSource" in my local and it is successful. Someone who can help to check the issue when running on GitHub.

Thanks,

**Comment by thienquach87** [comment]
Here is the PR for fixing a major ticket(LPP), so someone help to review it ASAP
Thanks,

**Comment by naraandrade** [comment]
Hi @thienquach87, the repository of liferay-zulu is not used anymore. The PRs need to be sent to liferay-workflow, that's why we didn't noticed this was waiting for review. I'll resent it there and will review the code asap.

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Resent here: https://github.com/liferay-workflow/liferay-portal/pull/908.

**Pull request closed without merging**
