### PR TITLE
LPS-154878 Display toggle to define a state field and display select to define defaultValue

### PR DESCRIPTION
**Pull request by naraandrade**
Story: [LPS-152677](https://issues.liferay.com/browse/LPS-152677)

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by MariMalta** [comment]
Just started reviewing :)

**Review by cgmonte — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
