### PR TITLE
LPS-148387

### PR DESCRIPTION
**Pull request by mbowerman**
Related Issue: https://issues.liferay.com/browse/LPS-148387

Hi Zulu team,

This is a follow-up pull to https://github.com/liferay-zulu/liferay-portal/pull/30, which already passed your review and was forwarded to Brian Chan. Brian Chan wanted some changes to the pull so I am re-sending the pull here with the requested changes for your further review.

See Brian Chan's feedback [here](https://github.com/brianchandotcom/liferay-portal/pull/114228#issuecomment-1060916182)

### CODE REVIEW

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @mbowerman, can you please check if these failures are related to your changes? Thanks

**Comment by mbowerman** [comment]
Doesn't look related @liferay-forms

**Comment by seltong** [comment]
Just started reviewing :)

**Comment by seltong** [comment]
ci:test:calendar

**Comment by seltong** [comment]
ci:test:calendar

**Review by seltong — APPROVED** [review]

**Comment by seltong** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @mbowerman, can you please check if these failures are related to your changes? Thanks

**Comment by MarinhoFeliphe** [comment]
Hi @mbowerman,

the liferay-forms is just a bot that support us to track the ci issues, don't worry if it mentions you.

**Comment by MarinhoFeliphe** [comment]
ci:test:calendar

**Comment by liferay-forms** [comment]
Hey @mbowerman, can you please check if these failures are related to your changes? Thanks

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by liferay-forms** [comment]
Hey @mbowerman, can you please check if these failures are related to your changes? Thanks

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @mbowerman, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @mbowerman, can you please check if these failures are related to your changes? Thanks

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @mbowerman, can you please check if these failures are related to your changes? Thanks

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Pull request closed without merging**
